AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/*'
    - 'vendor/**/*'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'config/environment.rb'
    - 'config/routes.rb'
    - 'app/controllers/notifications_controller.rb'
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Rails:
  Enabled: true

Rails/InverseOf:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/ExtraSpacing:
  Exclude:
    - 'bin/*'

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - 'Rakefile'
    - 'lib/tasks/*.rake'

Style/IfUnlessModifier:
  Enabled: false

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  ()
    '%i': '[]'
    '%q': ()
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': '[]'
    '%W': '[]'
    '%x': ()

Style/StringLiterals:
  Exclude:
    - 'bin/*'
